subgraphs:
  accounts:
    routing_url: http://localhost:4001/query
    schema:
      file: ./services/accounts/graph/accounts.graphql
  reviews:
    routing_url: http://localhost:4004/query
    schema:
      file: ./services/reviews/graph/reviews.graphql
  products:
    routing_url: http://localhost:4003/query
    schema:
      file: ./services/products/graph/products.graphql
  # inventory:
  #   routing_url: http://localhost:4002/query
  #   schema:
  #     file: ./services/inventory/graph/inventory.graphql