subgraphs:
  accounts:
    routing_url: http://localhost:4001/graphql
    schema:
      file: ./services/accounts/accounts.graphql
  reviews:
    routing_url: http://localhost:4002/graphql
    schema:
      file: ./services/reviews/reviews.graphql
  products:
    routing_url: http://localhost:4003/graphql
    schema:
      file: ./services/products/products.graphql
  inventory:
    routing_url: http://localhost:4004/graphql
    schema:
      file: ./services/inventory/inventory.graphql