// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	Upc              string  `json:"upc"`
	Weight           int     `json:"weight"`
	Price            int     `json:"price"`
	InStock          bool    `json:"inStock"`
	ShippingEstimate float64 `json:"shippingEstimate"`
}

func (Product) IsEntity() {}
